-- Create HASH user
WHENEVER SQLERROR CONTINUE

DROP USER &1 CASCADE;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER &1 IDENTIFIED BY "hash" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "USERS";

GRANT CREATE SESSION TO &1.;
GRANT CREATE TABLE TO &1.;
-- For unwrapper:
GRANT CREATE PROCEDURE TO &1.;