-- Create HASH user
WHENEVER SQLERROR CONTINUE

def v_username='&1.'
def v_password='&2.'

DROP USER &v_username. CASCADE;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER &v_username. IDENTIFIED BY "&v_password." DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "USERS";

GRANT CREATE SESSION TO &v_username.;
GRANT CREATE TABLE TO &v_username.;
-- For unwrapper:
GRANT CREATE PROCEDURE TO &v_username.;