WHENEVER SQLERROR EXIT SQL.SQLCODE

SET LINES 1000

DEF P_OWNER = '&1'
DEF P_VERS  = '&2'
DEF P_SER   = '&3'
DEF P_PATCH = '&4'

CREATE OR REPLACE FUNCTION GET_HIGH_VALUE_AS_STRING (
    P_OWNER         IN VARCHAR2,
    P_TABLENAME     IN VARCHAR2,
    P_PATITIONNAME  IN VARCHAR2
) RETURN VARCHAR2
IS
   V_LONGVAL LONG;
BEGIN
  SELECT HIGH_VALUE INTO V_LONGVAL
    FROM ALL_TAB_PARTITIONS
   WHERE TABLE_OWNER = P_OWNER
     AND TABLE_NAME = P_TABLENAME
     AND PARTITION_NAME = P_PATITIONNAME;

  RETURN SUBSTR(V_LONGVAL, 1, 200);
END;
/

SET SERVEROUT ON

-- BRING PARTITION COLUMNS BACK TO NOT NULL
DECLARE
  V_CMD CLOB;
BEGIN
  FOR I IN (select table_name from sys.user_tables where table_name like 'T\_%' escape '\')
  LOOP
    V_CMD := 'ALTER TABLE ' || DBMS_ASSERT.SQL_OBJECT_NAME(I.TABLE_NAME) || '
              MODIFY ( "ORAVERSION" NOT NULL,
                       "ORASERIES"  NOT NULL,
                       "ORAPATCH"   NOT NULL )';
    DBMS_OUTPUT.PUT_LINE(V_CMD || ';');
    EXECUTE IMMEDIATE V_CMD;
  END LOOP;
END;
/

-- EXCHANGE TABLES
DECLARE
  V_OWNER VARCHAR2(30) := UPPER('&P_OWNER');
  V_ORAVERSION T_PARAMETER.ORAVERSION%TYPE := '&P_VERS.';
  V_ORASERIES  T_PARAMETER.ORASERIES%TYPE := '&P_SER.';
  V_ORAPATCH   T_PARAMETER.ORAPATCH%TYPE := &P_PATCH.;
  ---
  V_PNAME VARCHAR2(100);
  V_HV    VARCHAR2(100);
  V_OWNER_TNAME VARCHAR2(100);
  V_DID_SMTG BOOLEAN := FALSE;

  --------------------------------------------

  FUNCTION IS_EMPTY (
    P_OWNER         IN VARCHAR2,
    P_TABLENAME     IN VARCHAR2
  ) RETURN BOOLEAN
  IS
    V_RES NUMBER;
  BEGIN
    -- DBMS_OUTPUT.PUT_LINE('SELECT 1 FROM DUAL WHERE EXISTS (SELECT 1 FROM ' || DBMS_ASSERT.ENQUOTE_NAME(P_OWNER) || '.' || DBMS_ASSERT.ENQUOTE_NAME(P_TABLENAME) || ')');
    EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL WHERE EXISTS (SELECT 1 FROM ' || DBMS_ASSERT.ENQUOTE_NAME(P_OWNER) || '.' || DBMS_ASSERT.ENQUOTE_NAME(P_TABLENAME) || ')'
    INTO V_RES;
    RETURN FALSE;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN TRUE;
  END;

  --------------------------------------------

  FUNCTION GEN_PART_HV (
    P_OWNER         IN VARCHAR2,
    P_TABLE_NAME     IN VARCHAR2
  ) RETURN VARCHAR2
  IS
    V_HV VARCHAR2(50);
  BEGIN
    SELECT LISTAGG(DECODE(COLUMN_NAME,'ORASERIES',DBMS_ASSERT.ENQUOTE_LITERAL(V_ORASERIES),'ORAVERSION',DBMS_ASSERT.ENQUOTE_LITERAL(V_ORAVERSION),'ORAPATCH',V_ORAPATCH),', ') WITHIN GROUP(ORDER BY COLUMN_POSITION)
    INTO   V_HV
    FROM   ALL_PART_KEY_COLUMNS
    WHERE  OWNER=P_OWNER
    AND    NAME=P_TABLE_NAME
    AND    OBJECT_TYPE='TABLE';

    RETURN V_HV;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN '';
  END;

  --------------------------------------------

  FUNCTION GET_PART_NAME (
    P_OWNER          IN VARCHAR2,
    P_TABLE_NAME     IN VARCHAR2,
    P_HV             IN VARCHAR2
  ) RETURN VARCHAR2
  IS
    V_PART_NAME VARCHAR2(30);
  BEGIN
    SELECT PARTITION_NAME
    INTO   V_PART_NAME
    FROM   ALL_TAB_PARTITIONS
    WHERE  TABLE_OWNER=P_OWNER
    AND    TABLE_NAME=P_TABLE_NAME
    AND    GET_HIGH_VALUE_AS_STRING(TABLE_OWNER,TABLE_NAME,PARTITION_NAME) = '( ' || P_HV || ' )';

    RETURN V_PART_NAME;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN '';
  END;

  --------------------------------------------

  PROCEDURE RUN_CMD (P_CMD CLOB)
  IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(P_CMD || ';');
    EXECUTE IMMEDIATE P_CMD;
    V_DID_SMTG := TRUE;
  END;

  --------------------------------------------

BEGIN
  FOR I IN (SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME)
  LOOP

    IF IS_EMPTY(USER,I.TABLE_NAME)
    THEN
      DBMS_OUTPUT.PUT_LINE( '--- ' || I.TABLE_NAME || ' - EMPTY');
      CONTINUE;
    END IF;

    V_OWNER_TNAME := DBMS_ASSERT.ENQUOTE_NAME(V_OWNER) || '.' || DBMS_ASSERT.ENQUOTE_NAME(I.TABLE_NAME);

    V_HV := GEN_PART_HV(V_OWNER,I.TABLE_NAME);
    -- DBMS_OUTPUT.PUT_LINE('V_HV: ' || V_HV);

    -- NULL V_HV = Non-partitioned table.

    IF V_HV IS NULL
    THEN
      IF I.TABLE_NAME = 'DM_CONTENTS'
      THEN
        RUN_CMD('INSERT /*+ APPEND */ INTO ' || V_OWNER_TNAME || ' SELECT * FROM ' || DBMS_ASSERT.ENQUOTE_NAME(I.TABLE_NAME) || ' A WHERE NOT EXISTS (SELECT 1 FROM ' || V_OWNER_TNAME || ' B WHERE A.MD5_HASH = B.MD5_HASH)');
      ELSIF I.TABLE_NAME = 'DM_CODES'
      THEN
        RUN_CMD('INSERT /*+ APPEND */ INTO ' || V_OWNER_TNAME || ' SELECT * FROM ' || DBMS_ASSERT.ENQUOTE_NAME(I.TABLE_NAME) || ' A WHERE NOT EXISTS (SELECT 1 FROM ' || V_OWNER_TNAME || ' B WHERE A.MD5_HASH = B.MD5_HASH)');
      ELSE
        RAISE_APPLICATION_ERROR(-20000,'Unknown Table');
      END IF;
    ELSE
      V_PNAME := GET_PART_NAME(V_OWNER,I.TABLE_NAME,V_HV);
      IF V_PNAME IS NOT NULL
      THEN
        RUN_CMD('ALTER TABLE ' || V_OWNER_TNAME || ' EXCHANGE PARTITION ' || DBMS_ASSERT.ENQUOTE_NAME(V_PNAME) || ' WITH TABLE ' || DBMS_ASSERT.ENQUOTE_NAME(I.TABLE_NAME) || ' INCLUDING INDEXES WITH VALIDATION');
      ELSE
        RUN_CMD('ALTER TABLE ' || V_OWNER_TNAME || ' ADD PARTITION VALUES ( ' || V_HV || ' )');
        V_PNAME := GET_PART_NAME(V_OWNER,I.TABLE_NAME,V_HV);
        RUN_CMD('ALTER TABLE ' || V_OWNER_TNAME || ' EXCHANGE PARTITION ' || DBMS_ASSERT.ENQUOTE_NAME(V_PNAME) || ' WITH TABLE ' || DBMS_ASSERT.ENQUOTE_NAME(I.TABLE_NAME) || ' INCLUDING INDEXES WITH VALIDATION');
      END IF;
    END IF;
  END LOOP;
  IF V_DID_SMTG
  THEN
    -- Add here any optional code to do after the exchange.
    NULL;
  ELSE
    DBMS_OUTPUT.PUT_LINE('---');
    DBMS_OUTPUT.PUT_LINE('--- ATTENTION: ALL TABLES ARE EMPTY');
  END IF;
END;
/

DROP FUNCTION GET_HIGH_VALUE_AS_STRING;

EXIT 0
