-- Run diff generation process for ALL every database.
WHENEVER SQLERROR CONTINUE

CREATE TABLE "DIFF_CODES"
(
    "MD5_HASH_FROM" RAW(16) NOT NULL,
    "MD5_HASH_TO"   RAW(16) NOT NULL,
    "DIFF_CODE"     CLOB    NOT NULL,
    CONSTRAINT DIFF_CODES_PK PRIMARY KEY ("MD5_HASH_FROM", "MD5_HASH_TO"),
    CONSTRAINT DIFF_CODES_F1 FOREIGN KEY ("MD5_HASH_FROM") REFERENCES DM_CODES ("MD5_HASH") ON DELETE CASCADE,
    CONSTRAINT DIFF_CODES_F2 FOREIGN KEY ("MD5_HASH_TO")   REFERENCES DM_CODES ("MD5_HASH") ON DELETE CASCADE
)
COMPRESS NOLOGGING;

CREATE INDEX "DIFF_CODES_F1" ON "DIFF_CODES" ("MD5_HASH_FROM");
CREATE INDEX "DIFF_CODES_F2" ON "DIFF_CODES" ("MD5_HASH_TO");

CREATE TABLE "DIFF_CONTENTS"
(
    "MD5_HASH_FROM" RAW(16) NOT NULL,
    "MD5_HASH_TO"   RAW(16) NOT NULL,
    "DIFF_CODE"     CLOB    NOT NULL,
    CONSTRAINT DIFF_CONTENTS_PK PRIMARY KEY ("MD5_HASH_FROM", "MD5_HASH_TO"),
    CONSTRAINT DIFF_CONTENTS_F1 FOREIGN KEY ("MD5_HASH_FROM") REFERENCES DM_CONTENTS ("MD5_HASH") ON DELETE CASCADE,
    CONSTRAINT DIFF_CONTENTS_F2 FOREIGN KEY ("MD5_HASH_TO")   REFERENCES DM_CONTENTS ("MD5_HASH") ON DELETE CASCADE
)
COMPRESS NOLOGGING;

CREATE INDEX "DIFF_CONTENTS_F1" ON "DIFF_CONTENTS" ("MD5_HASH_FROM");
CREATE INDEX "DIFF_CONTENTS_F2" ON "DIFF_CONTENTS" ("MD5_HASH_TO");

WHENEVER SQLERROR EXIT SQL.SQLCODE

DEF P_CRED   = '&1' 
DEF P_FOLDER = '&2' 

@&P_FOLDER./diff_calculate_all.sql '&P_CRED.' 'all'

exit