# Folder where the database patches are placed. The patches can also be placed in sub-folders of the directory specified below.
source_folder : "/Volumes/Untitled/Rodrigo/ORACHKSUM/DB\ Install"

# Folder in RW mode on your compute shared with VM to process files.
shared_folder : "/Users/rodrigo.jorge/Desktop/extract"

# Path of the folder mounted within the VM.
VM_folder  : "/media/sf_Patch/"

# Path of the folder mounted within the VM.
VM_IP_address  : "192.168.56.101"

# Oracle SID. Must be included in /etc/oratab
mysid : "orcl"

# Folder to store the final generated DB dump
dump_folder : "/Volumes/Samsung_T3/OraSum/files/exp"

# Files in "user_scripts" folder that will run before and after the final expdp. script_types can be "shell", "sql" or "yml".
user_expdp_pre  :
- { file : "preActions.sql" , type : "sql" , task_action : "Pre Actions" }
- { file : "externalDir.sql" , type : "sql" , task_action : "Create External Directory" }

user_expdp_post :
- { file : "postActions.sql" , type : "sql" , task_action : "Post Actions" }

# User that will hold your tables outputs and be exported after each execution. If the database is CDB, "C##" will be automatically inserted if not.
dump_user : hash

# User pass
dump_pass : hash

# This parameter will skip execution for patches that already have a dump file generated in "dump_folder".
skip_dump_exists: true
