# Patch location type: Can be "folder" or "bucket"
# Patch location path: Can be the local folder path or the bucket name.
# Folder where the database patches are placed. The patches can also be placed in sub-folders of the directory specified below.
patch_location_type : bucket
patch_location_path : patches

# Folder in RW mode on local compute and shared with the VM. It is used to move the patches to the VMs and also to copy back the expdp output.
stage_folder : "/u01/patch_automation/stage"
shared_folder : "/u02"

# Path of the folder mounted within the VM. This is the path of the "shared_folder" in the VM.
VM_folder  : "/u02"

# Oracle SID of the database that we are collecting data from. Must be included in /etc/oratab for oraenv utility.
default_sid : "orcl"

# Folder to store the final generated files.
output_folder : "/u01/patch_automation/output"

# Download utility info, if you are using one.
# wget https://github.com/MarisElsins/getMOSPatch/raw/master/getMOSPatch.jar
downloader_tool : "/u01/patch_automation/getMOSPatch.jar"
downloader_user : ""
downloader_pass : ""

# Files in "user_scripts" folder that will run before and after the final expdp. script_types can be "shell", "sql" or "yml".
user_expdp_pre  :
# - { file : "bugsGet.yml" , folder : "user_scripts/odbfcl/adb_load_bugs_fixed" , type : "yml", task_action : "Generate fixed bugs list for ORACLE_HOME" }
# - { file : "chksumGet.yml" , folder : "user_scripts/odbfcl/adb_load_filechksum" , type : "yml", task_action : "Generate chksum for ORACLE_HOME" }
# - { file : "fileGet.yml" , folder : "user_scripts/odbfcl/adb_load_txtcollection_files" , type : "yml", task_action : "Collect non-binary files from ORACLE_HOME" }
# - { file : "symbolGet.yml" , folder : "user_scripts/odbfcl/adb_load_symbols" , type : "yml", task_action : "Get all symbols on ORACLE_HOME binaries and libs" }
# - { file : "tables_recreate.yml" , folder : "user_scripts/odbfcl" , type : "yml" , task_action : "Recreate tables" }
# - { file : "hashGet.yml" , folder : "user_scripts/odbfcl/extract" , type : "yml", task_action : "Collect Database Info" }
- { file : "runExtractor.yml" , folder : "user_scripts/odbfcl" , type : "yml", task_action : "Collect DB Info" }
- { file : "externalDir.yml" , type : "yml" , task_action : "Create External Directory" }

user_expdp_post :
- { file : "def_adb_variables.yml" , folder : "user_scripts/odbfcl" , type : "yml", task_action : "Define ansible ADB variables" }
# - { file : "tables_recreate_adb.yml" , folder : "user_scripts/odbfcl" , type : "yml", task_action : "Recreate tables in ADB" }
- { file : "adb_load_expdp.yml" , folder : "user_scripts/odbfcl/adb_load_expdp" , type : "yml", task_action : "impdp files from OS to ADB" }
# - { file : "adb_load_bugs_fixed.yml" , folder : "user_scripts/odbfcl/adb_load_bugs_fixed" , type : "yml", task_action : "Load fixed bugs list for ORACLE_HOME in ADB" }
# - { file : "adb_load_filechksum.yml" , folder : "user_scripts/odbfcl/adb_load_filechksum" , type : "yml", task_action : "Load chksum for ORACLE_HOME in ADB" }
# - { file : "adb_load_symbols.yml" , folder : "user_scripts/odbfcl/adb_load_symbols" , type : "yml", task_action : "Load chksum for ORACLE_HOME in ADB" }
# - { file : "adb_load_txtcollection_files.yml" , folder : "user_scripts/odbfcl/adb_load_txtcollection_files" , type : "yml", task_action : "Load non-binary files from ORACLE_HOME in ADB" }
- { file : "diff_calculate.yml" , folder : "user_scripts/odbfcl/diff_calculate" , type : "yml", task_action : "Generate differences between 2 releases" }

# User that will hold your tables outputs and be exported after each execution. If the database is CDB, "C##" will be automatically be appended.
dump_user : hash
dump_pass : hash
dump_dir_name : expdir_hash

# OCI Information to deploy VM
oci_compartment_id : ocid1.compartment.oc1..xxx

# OCI Information to upload objects to OS
oci_namespace: xxx
oci_adb_bucket: xxx

# OCI Information to connect and load in ADB
oci_adb_user: xxx
oci_adb_pass: xxx
oci_adb_tns:  xxx_tp
oci_adb_credential: XXX
oci_adb_os_url_prefix: https://objectstorage.us-ashburn-1.oraclecloud.com/n/xxx/b/xxx/o
oci_adb_use_wallet: true

###########################
### For loader.yml only ###
###########################

# Files in "user_scripts" folder that will run before and after the final expdp.
user_impdp_pre  :
- { file : "pre_prepare_dump_file.yml" , folder : "user_scripts/odbfcl/adb_load_expdp" , type : "yml", task_action : "Prepare files for impdp" }

user_impdp_post :
- { file : "post_remove_dump_file.yml" , folder : "user_scripts/odbfcl/adb_load_expdp" , type : "yml", task_action : "Clean files used for impdp" }
- { file : "mark_dump_file_loaded.yml" , folder : "user_scripts/odbfcl/adb_load_expdp" , type : "yml", task_action : "Mark dpfile as loaded." }
