# OCI Mode? If true, script will load and run in OCI move, otherwise, VBox.
oci_mode : true

# This parameter will skip execution for patches that already have a dump file generated in "dump_folder" ("output_folder"/expdp).
skip_dump_exists: true

# If true, will only deploy the patch and skip the expdp and the pre/post steps.
only_deploy_patch: false

# Target DB version where dumps will be imported
target_db_version: 19 # Used to check if version parameter will be required on expdp

# Download Mode? If true, script will try to download the patch if not found in "source_folder".
download_patch : true

# Stop when patch zip is not found? Control if the code will fail or just skip that patch.
error_on_no_patch : true