- name: Variables not provided
  fail:
    msg: "Variables downloader_tool / downloader_user / downloader_pass must be defined when download_patch is true."
  when: ( downloader_tool is undefined or downloader_user is undefined
   or (downloader_tool|length == 0) or (downloader_user|length == 0)) and download_patch == true

- name: "Check if {{ downloader_tool }} exists"
  stat:
    path: "{{ downloader_tool }}"
  register: downloader_tool_result
  when: download_patch == true

- name: Tool does not exist
  fail:
    msg: "{{ downloader_tool }} must exist when download_patch is true."
  when: download_patch == true and downloader_tool_result.stat.exists == false

- name: Check patch_location_type variable
  fail:
    msg: 'patch_location_type must be "folder" or "bucket".'
  when: patch_location_type != "folder" and patch_location_type != "bucket"

- name: Check oci_adb_use_wallet variable
  fail:
    msg: 'oci_adb_use_wallet must be "true" or "false".'
  when: oci_adb_use_wallet != true and oci_adb_use_wallet != false