- name: "Load base snapshot {{ vm_snapshot }}"
  shell: |
       set -e
       v_snapshot="{{ vm_snapshot }}"
       v_disk='/dev/mapper/vg_u01-lv_u01'
       pkill -9 -U oracle || true
       sleep 5
       umount -l -f /u01 || true
       sleep 5
       lvchange -a n ${v_disk}
       lvconvert --merge -i 1 -v ${v_disk}_${v_snapshot}
       lvchange -a n ${v_disk}
       lvchange -a y ${v_disk}
       while :
       do
         if ! lvs -a | grep lv_u01_${v_snapshot}
         then
           break
         fi
         dmsetup status ${v_disk}
         sleep 1
       done
       v_size=$(lvs --noheadings -o seg_size ${v_disk})
       lvcreate --size ${v_size} --snapshot --name lv_u01_${v_snapshot} ${v_disk}
       mount /u01
  become: true
  become_user: root
  delegate_to: "{{ vm_ip_address }}"