### Will import all dumps to a given database.

- name : Define version
  set_fact:
    patch_list:    "{{ item.patch_list }}"
  with_items: "{{ list_versions }}"
  when: item.id == db_version

- name : Define Cloud params
  set_fact:
    out_of_box_ru: "{{ item.out_of_box_ru | default(0) }}"
  with_items: "{{ list_info_oci }}"
  when: item.id == db_version

#- fail:
#    msg: "Stop here."

- name : Check if there is any PSU
  set_fact:
    total_psus: "{{ lookup('vars', patch_list) | json_query(filter_qry) | count }}"
  vars:
    filter_qry: "[?type=='PSU'].id"

- name : Check if there is any BP
  set_fact:
    total_bps: "{{ lookup('vars', patch_list) | json_query(filter_qry) | count }}"
  vars:
    filter_qry: "[?type=='BP'].id"

- name : Check if there is any RU
  set_fact:
    total_rus: "{{ lookup('vars', patch_list) | json_query(filter_qry) | count }}"
  vars:
    filter_qry: "[?type=='RU'].id"

###############################

# Execute for base release if there is at least 1 PSU for that version
- include: "impdp_file_adb.yml"
  vars:
    patch : { type : PSU , id : 0, patch_number : 0 }
  when:
    - total_psus != "0"
    - 0 == (param_patch | int)      or param_patch == -1
    - 0 >= (param_patch_from | int) or param_patch_from == -1
    - 0 <= (param_patch_to | int)   or param_patch_to == -1
    - param_type is undefined or param_type == "PSU"

# Execute for base release if there is at least 1 BP for that version
- include: "impdp_file_adb.yml"
  vars:
    patch : { type : BP , id : 0, patch_number : 0 }
  when:
    - total_bps != "0"
    - 0 == (param_patch | int)      or param_patch == -1
    - 0 >= (param_patch_from | int) or param_patch_from == -1
    - 0 <= (param_patch_to | int)   or param_patch_to == -1
    - param_type is undefined or param_type == "BP"

# Execute for base release if there is at least 1 RU for that version
- include: "impdp_file_adb.yml"
  vars:
    patch : { type : RU , id : "{{ out_of_box_ru }}" , patch_number : 0 }
  when:
    - total_rus != "0"
    - (out_of_box_ru | int) == (param_patch | int)      or param_patch == -1
    - (out_of_box_ru | int) >= (param_patch_from | int) or param_patch_from == -1
    - (out_of_box_ru | int) <= (param_patch_to | int)   or param_patch_to == -1
    - param_type is undefined or param_type == "RU"

###############################

# Execute for every PSU / BP / OJVM / RU / RUR
- include: "impdp_file_adb.yml"
  loop: "{{ lookup('vars', patch_list) | flatten(levels=1) }}"
  loop_control:
    loop_var: patch
    label: "{{ patch.id }}"
  when:
    - patch.id == (param_patch | int)      or param_patch == -1
    - patch.id >= (param_patch_from | int) or param_patch_from == -1
    - patch.id <= (param_patch_to | int)   or param_patch_to == -1
    - patch.id > (out_of_box_ru | int)     or patch.type != "RU"     # When RU, skip patch.id lower or equal to out_of_box_ru
    - param_type is undefined or param_type == patch.type