### Will import all dumps to a given database.

- name : Define version
  set_fact:
    patch_list:       "{{ item.patch_list }}"
    db_version_short: "{{ db_version | replace('.','') }}"
  with_items: "{{ list_versions }}"
  when: item.id == db_version

- name : Define Cloud params
  set_fact:
    out_of_box_id: "{{ item.out_of_box_id | default(-1, true) }}"
  with_items: "{{ list_info_oci }}"
  when: item.id == db_version

#- fail:
#    msg: "Stop here."

- name : Check if there is any PSU
  set_fact:
    total_psus: "{{ lookup('vars', patch_list) | json_query(filter_qry) | count }}"
  vars:
    filter_qry: "[?type=='PSU'].id"

###############################

# Execute for base release if there is at least 1 PSU for that version
- include: "impdp_file_adb.yml"
  vars:
    patch : { type : BASE , id : 0, patch_number : 0 }
  when:
    - total_psus != "0"
    - 0 == (param_patch | float)      or param_patch == -1
    - 0 >= (param_patch_from | float) or param_patch_from == -1
    - 0 <= (param_patch_to | float)   or param_patch_to == -1
    - param_type is undefined or param_type == "PSU"

# Execute for base release if there is at least 1 RU for that version
- include: "impdp_file_adb.yml"
  vars:
    patch : { type : BASE , id : "{{ out_of_box_id }}" , patch_number : 0 }
  when:
    - (out_of_box_id | float) != -1
    - (out_of_box_id | float) == (param_patch | float)      or param_patch == -1
    - (out_of_box_id | float) >= (param_patch_from | float) or param_patch_from == -1
    - (out_of_box_id | float) <= (param_patch_to | float)   or param_patch_to == -1
    - param_type is undefined or param_type == "RU"

###############################

# Execute for every PSU / BP / OJVM / RU / RUR / MRP
- include: "impdp_file_adb.yml"
  loop: "{{ lookup('vars', patch_list) | flatten(levels=1) }}"
  loop_control:
    loop_var: patch
    label: "{{ patch.id }}"
  when:
    - patch.id == (param_patch | float)      or param_patch == -1
    - patch.id >= (param_patch_from | float) or param_patch_from == -1
    - patch.id <= (param_patch_to | float)   or param_patch_to == -1
    - patch.id > (out_of_box_id | float)     or patch.type != "RU"     # When RU, skip patch.id lower or equal to out_of_box_id
    - (patch.version | default(db_version)) == db_version
    - param_type is undefined or param_type == patch.type