# Skip the dump part if no expdp was executed
- block:

  - name: "Copy {{ dump_file_prefix }}.dmp to repository"
    copy:
      src: "{{ shared_folder }}/{{ dump_file_prefix }}.dmp"
      dest: "{{ output_folder }}/expdp"

  - name: "Copy {{ dump_file_prefix }}.log to repository"
    copy:
      src: "{{ shared_folder }}/{{ dump_file_prefix }}.log"
      dest: "{{ output_folder }}/expdp"

  - name : "Remove file {{ dump_file_prefix }}.dmp"
    file:
      state: absent
      path: "{{ shared_folder }}/{{ dump_file_prefix }}.dmp"

  - name : "Remove file {{ dump_file_prefix }}.log"
    file:
      state: absent
      path: "{{ shared_folder }}/{{ dump_file_prefix }}.log"

  # This task will mark file as loaded
  - include: run_script.yml
    vars:
      script_param: { file : "mark_dump_file_loaded.yml" , folder : "user_scripts/odbfcl/adb_load_expdp" , type : "yml", task_action : "Mark dpfile as loaded." }

  when: not only_deploy_patch

- name : Remove unzipped patch folder
  file:
    state: absent
    path: "{{ unzip_patch_folder }}"
  when: perform_patch_actions

- name : Remove zipped patch
  file:
    state: absent
    path: "{{ shared_folder }}/{{ db_patch | basename }}"
  when: perform_patch_actions and patch.apply_method is defined and patch.apply_method == "gold_image"

# Here I don't check for perform_patch_actions as in some cases (like for LVM image usage) the patch will still be downloaded.
- name: Remove file downloaded from OCI Bucket
  file:
    state: absent
    path: "{{ db_patch }}"
  when: patch_location_type == "bucket" and db_patch != ""

- name : Remove PatchSearch.xml
  file:
    state: absent
    path: "{{ shared_folder }}/PatchSearch.xml"
  when: perform_patch_actions

- name : Define latest processed
  set_fact:
    latest_processed: "{{ db_version }}|{{ patch.type }}|{{ patch.id }}"

### Save latest applied PSU/RU as Base Snapshot for OJVM.
- block:

  - name : Generate Snapshot Name - VBox Mode
    set_fact:
      save_snapshot: "{{ db_version }} {{ patch.type }} {{ base_OJVM_id }}"
    when: not oci_mode

  - include: vbox_savestate.yml
    when: not oci_mode

  - name : Generate Snapshot Name - LVM Mode
    set_fact:
      save_snapshot: "{{ db_version_short }}_{{ patch.type }}_{{ base_OJVM_id }}"
    when: oci_mode

  - include: lvm_savestate.yml
    when: oci_mode

  when: base_OJVM_line is defined and ( patch.type == "PSU" or patch.type == "RU" ) and base_OJVM_line == latest_processed