- name: "Run Shell-script - {{ shell_param.task_action }}"
  shell: |
       export ORACLE_HOME ORACLE_SID
       sh {{ VM_folder }}/{{ shell_param.folder | default('user_scripts') }}/{{ shell_param.file }} {{ shell_param.params | default('') }}
  environment:
    ORACLE_HOME: "{{ dbhome_locl }}"
    ORACLE_SID: "{{ mysid }}"
  args:
    chdir: "{{ VM_folder }}/{{ shell_param.folder | default('user_scripts') }}"
  register: shoutput
  become: true
  become_user: oracle
  delegate_to: "{{ vm_ip_address }}"

- name: Shell-script Output
  debug: msg="{{ shoutput.stdout_lines }}"