- name: "Run SQL to {{ task_action }}"
  shell: |
       export ORACLE_HOME ORACLE_SID
       {{ dbhome_locl }}/bin/sqlplus -s "/ as sysdba" @{{ VM_folder }}/{{ sql_folder }}/{{ sql_file }} {{ sql_parameters | default('') }}
  environment:
    ORACLE_HOME: "{{ dbhome_locl }}"
    ORACLE_SID: "{{ mysid }}"
  register: sqloutput
  become: true
  become_user: oracle
  delegate_to: "{{ VM_IP_address }}"

- name: SQL Output
  debug: msg="{{ sqloutput.stdout_lines }}"
