- name: Ensure shared disk "{{ shared_folder }}" is mounted
  shell: |
    set -eo pipefail
    if mount | grep -q -F ' {{ shared_folder }} '
    then
      echo ok
    else
      mount {{ shared_folder }}
    fi
  become: true
  become_user: root
  when: oci_mode == true

- name: Copy patch SQL to shared folder
  synchronize:
    src: patch_sql/
    dest: "{{ shared_folder }}/patch_sql/"
    delete: yes

- name: Copy user SQL to shared folder
  synchronize:
    src: user_scripts/
    dest: "{{ shared_folder }}/user_scripts/"
    delete: yes

- name : Check parameter param_patch
  set_fact:
    param_patch: -1
  when: param_patch is undefined

- name : Check parameter param_patch_from
  set_fact:
    param_patch_from: -1
  when: param_patch_from is undefined

- name : Check parameter param_patch_to
  set_fact:
    param_patch_to: -1
  when: param_patch_to is undefined

- name : Define latest processed as null
  set_fact:
    latest_processed: ""

- name : Define patch_location_bucket
  set_fact:
    patch_location_bucket: "{{ patch_location_path }}"
    patch_location_path: "{{ stage_folder }}"
  when: patch_location_type == "bucket"