## This code will take a snapshot named "vm_snapshot" for the VM. It will later be used as a base release for OJVMs.

# Save latest machine image if not already
- name: "Create new VM snapshot \"{{ vm_snapshot }}\" if not exists."
  shell: |
       MACHINE="{{ vm_machine }}"
       SNAPSHOT="{{ vm_snapshot }}"
       if ! $(VBoxManage showvminfo --machinereadable "$MACHINE" | grep -q "^SnapshotName.*=\"$SNAPSHOT\"")
       then
         VBoxManage snapshot "$MACHINE" take "$SNAPSHOT"
       fi
       until $(VBoxManage showvminfo --machinereadable "$MACHINE" | grep -q ^VMState=.running.)
       do
         sleep 1
       done