- name: Upload file to object storage
  oci_object_storage_object:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_bucket }}"
    object_name: "{{ oci_upload_file | regex_replace('^.*\\/', '') }}"
    src: "{{ oci_upload_file }}"
    state: present
  register: oci_action
  when: object_action == "create"

- name: Remove file from object storage
  oci_object_storage_object:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_bucket }}"
    object_name: "{{ oci_upload_file | regex_replace('^.*\\/', '') }}"
    state: absent
  register: oci_action
  when: object_action == "remove"