- name: Upload file to object storage
  oci_object_storage_object:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_upload_bucket }}"
    object_name: "{{ oci_object_name }}"
    src: "{{ oci_upload_file }}"
    state: present
  register: oci_action
  when: object_action == "create"

- name: Remove file from object storage
  oci_object_storage_object:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_upload_bucket }}"
    object_name: "{{ oci_object_name }}"
    state: absent
  register: oci_action
  when: object_action == "remove"