WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SYMBOLS_LOAD PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE T_SYMBOLS_LOAD
(
  SOURCE_FILE  VARCHAR2(50)  NOT NULL,
  FILE_NAME    VARCHAR2(100) NOT NULL,
  SYMBOL_TYPE  VARCHAR2(1)   NOT NULL,
  SYMBOL_NAME  VARCHAR2(500) NOT NULL
)
COMPRESS NOLOGGING;