WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE &v_username.."T_HASH_LOAD" PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE &v_username.."T_HASH_LOAD"
(
  "OWNER"         VARCHAR2(128 CHAR),
  "NAME"          VARCHAR2(128 CHAR),
  "TYPE"          VARCHAR2(12 CHAR),
  "ORIGIN_CON_ID" NUMBER,
  "CON_ID"        NUMBER,
  "MD5_ENC"       RAW(16) NOT NULL,
  "SHA1_ENC"      RAW(20) NOT NULL,
  "CODE"          CLOB NOT NULL
)
COMPRESS NOLOGGING;