- name: Download file from object storage
  oci_object_storage_object_facts:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_manual_bucket }}"
    object_name: "{{ oci_download_file }}"
    auth_type: instance_principal
    dest: "{{ oci_dest_file }}"
  register: oci_action
  when: object_action == "download"

- name: List files from object storage
  oci_object_storage_object_facts:
    namespace_name: "{{ oci_namespace }}"
    bucket_name: "{{ oci_manual_bucket }}"
  register: oci_action
  when: object_action == "list"