WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET SERVEROUT ON ECHO OFF FEED OFF
DECLARE
  V_RESULT NUMBER;
BEGIN
  SELECT SUBSTR(VERSION,1,INSTR(VERSION,'.',1,1)-1) INTO V_RESULT FROM (SELECT VERSION FROM V$INSTANCE);
  DBMS_OUTPUT.PUT_LINE(V_RESULT);
EXCEPTION
  WHEN OTHERS THEN
      NULL;
END;
/
EXIT