SET SERVEROUT ON ECHO OFF FEED OFF
DECLARE
  V_RESULT NUMBER;
BEGIN
  select 1 INTO V_RESULT from dual where SYS_CONTEXT('USERENV', 'CON_ID')=1;
  DBMS_OUTPUT.PUT_LINE('c##');
EXCEPTION
  WHEN OTHERS THEN
      NULL;
END;
/
EXIT