-- Create HASH user
WHENEVER SQLERROR CONTINUE

DROP USER &&1. CASCADE;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER &&1. IDENTIFIED BY "hash" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

GRANT UNLIMITED TABLESPACE TO &&1.;
GRANT CREATE SESSION TO &&1.;
GRANT "DBA" TO &&1.;