-- Create HASH user

DROP USER HASH CASCADE;

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER HASH IDENTIFIED BY "hash" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

GRANT UNLIMITED TABLESPACE TO HASH;
GRANT CREATE SESSION TO HASH;
GRANT "DBA" TO HASH;