WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE "T_TRIGGERS"
(
"OWNER" VARCHAR2(128 CHAR),
"TRIGGER_NAME" VARCHAR2(128 CHAR),
"TRIGGER_TYPE" VARCHAR2(16 CHAR),
"TRIGGERING_EVENT" VARCHAR2(246 CHAR),
"TABLE_OWNER" VARCHAR2(128 CHAR),
"BASE_OBJECT_TYPE" VARCHAR2(18 CHAR),
"TABLE_NAME" VARCHAR2(128 CHAR),
"COLUMN_NAME" VARCHAR2(4000 CHAR),
"REFERENCING_NAMES" VARCHAR2(422 CHAR),
"WHEN_CLAUSE" VARCHAR2(4000 CHAR),
"STATUS" VARCHAR2(8 CHAR),
"DESCRIPTION" VARCHAR2(4000 CHAR),
"ACTION_TYPE" VARCHAR2(11 CHAR),
"CROSSEDITION" VARCHAR2(7 CHAR),
"BEFORE_STATEMENT" VARCHAR2(3 CHAR),
"BEFORE_ROW" VARCHAR2(3 CHAR),
"AFTER_ROW" VARCHAR2(3 CHAR),
"AFTER_STATEMENT" VARCHAR2(3 CHAR),
"INSTEAD_OF_ROW" VARCHAR2(3 CHAR),
"FIRE_ONCE" VARCHAR2(3 CHAR),
"APPLY_SERVER_ONLY" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_AUDIT_POLICY_COLUMNS"
(
"OBJECT_SCHEMA" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"POLICY_NAME" VARCHAR2(128 CHAR),
"POLICY_COLUMN" VARCHAR2(128 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_AUDIT_UNIFIED_POLICIES"
(
"POLICY_NAME" VARCHAR2(128 CHAR),
"AUDIT_CONDITION" VARCHAR2(4000 CHAR),
"CONDITION_EVAL_OPT" VARCHAR2(9 CHAR),
"AUDIT_OPTION" VARCHAR2(128 CHAR),
"AUDIT_OPTION_TYPE" VARCHAR2(18 CHAR),
"OBJECT_SCHEMA" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"OBJECT_TYPE" VARCHAR2(23 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_COL_PRIVS"
(
"GRANTEE" VARCHAR2(128 CHAR),
"OWNER" VARCHAR2(128 CHAR),
"TABLE_NAME" VARCHAR2(128 CHAR),
"COLUMN_NAME" VARCHAR2(128 CHAR),
"GRANTOR" VARCHAR2(128 CHAR),
"PRIVILEGE" VARCHAR2(40 CHAR),
"GRANTABLE" VARCHAR2(3 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_REGISTRY_HISTORY"
(
"ACTION_TIME" TIMESTAMP (6),
"ACTION" VARCHAR2(30 CHAR),
"NAMESPACE" VARCHAR2(30 CHAR),
"VERSION" VARCHAR2(30 CHAR),
"ID" NUMBER,
"COMMENTS" VARCHAR2(255 CHAR),
"BUNDLE_SERIES" VARCHAR2(30 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_SCHEDULER_PROGRAMS"
(
"OWNER" VARCHAR2(128 CHAR),
"PROGRAM_NAME" VARCHAR2(128 CHAR),
"PROGRAM_TYPE" VARCHAR2(16 CHAR),
"PROGRAM_ACTION" VARCHAR2(4000 CHAR),
"NUMBER_OF_ARGUMENTS" NUMBER,
"ENABLED" VARCHAR2(5 CHAR),
"DETACHED" VARCHAR2(5 CHAR),
"SCHEDULE_LIMIT" INTERVAL DAY (3) TO SECOND (0),
"PRIORITY" NUMBER,
"WEIGHT" NUMBER,
"MAX_RUNS" NUMBER,
"MAX_FAILURES" NUMBER,
"MAX_RUN_DURATION" INTERVAL DAY (3) TO SECOND (0),
"HAS_CONSTRAINTS" VARCHAR2(5 CHAR),
"NLS_ENV" VARCHAR2(4000 CHAR),
"COMMENTS" VARCHAR2(4000 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_JOBS"
(
"JOB" NUMBER,
"LOG_USER" VARCHAR2(128 CHAR),
"PRIV_USER" VARCHAR2(128 CHAR),
"SCHEMA_USER" VARCHAR2(128 CHAR),
"LAST_DATE" DATE,
"LAST_SEC" VARCHAR2(8 CHAR),
"THIS_DATE" DATE,
"THIS_SEC" VARCHAR2(8 CHAR),
"NEXT_DATE" DATE,
"NEXT_SEC" VARCHAR2(8 CHAR),
"TOTAL_TIME" NUMBER,
"BROKEN" VARCHAR2(1 CHAR),
"INTERVAL" VARCHAR2(200 CHAR),
"FAILURES" NUMBER,
"WHAT" VARCHAR2(4000 CHAR),
"NLS_ENV" VARCHAR2(4000 CHAR),
"MISC_ENV" RAW(32),
"INSTANCE" NUMBER,
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_TAB_PRIVS"
(
"GRANTEE" VARCHAR2(128 CHAR),
"OWNER" VARCHAR2(128 CHAR),
"TABLE_NAME" VARCHAR2(128 CHAR),
"GRANTOR" VARCHAR2(128 CHAR),
"PRIVILEGE" VARCHAR2(40 CHAR),
"GRANTABLE" VARCHAR2(3 CHAR),
"HIERARCHY" VARCHAR2(3 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"TYPE" VARCHAR2(24 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_PRIV_AUDIT_OPTS"
(
"USER_NAME" VARCHAR2(128 CHAR),
"PROXY_NAME" VARCHAR2(128 CHAR),
"PRIVILEGE" VARCHAR2(40 CHAR),
"SUCCESS" VARCHAR2(10 CHAR),
"FAILURE" VARCHAR2(10 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_TS_QUOTAS"
(
"TABLESPACE_NAME" VARCHAR2(30 CHAR),
"USERNAME" VARCHAR2(128 CHAR),
"BYTES" NUMBER,
"MAX_BYTES" NUMBER,
"BLOCKS" NUMBER,
"MAX_BLOCKS" NUMBER,
"DROPPED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_OBJ_AUDIT_OPTS"
(
"OWNER" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"OBJECT_TYPE" VARCHAR2(23 CHAR),
"ALT" VARCHAR2(3 CHAR),
"AUD" VARCHAR2(3 CHAR),
"COM" VARCHAR2(3 CHAR),
"DEL" VARCHAR2(3 CHAR),
"GRA" VARCHAR2(3 CHAR),
"IND" VARCHAR2(3 CHAR),
"INS" VARCHAR2(3 CHAR),
"LOC" VARCHAR2(3 CHAR),
"REN" VARCHAR2(3 CHAR),
"SEL" VARCHAR2(3 CHAR),
"UPD" VARCHAR2(3 CHAR),
"REF" CHAR(3 CHAR),
"EXE" VARCHAR2(3 CHAR),
"CRE" VARCHAR2(3 CHAR),
"REA" VARCHAR2(3 CHAR),
"WRI" VARCHAR2(3 CHAR),
"FBK" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_STMT_AUDIT_OPTS"
(
"USER_NAME" VARCHAR2(128 CHAR),
"PROXY_NAME" VARCHAR2(128 CHAR),
"AUDIT_OPTION" VARCHAR2(40 CHAR),
"SUCCESS" VARCHAR2(10 CHAR),
"FAILURE" VARCHAR2(10 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_POLICIES"
(
"OBJECT_OWNER" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"POLICY_GROUP" VARCHAR2(128 CHAR),
"POLICY_NAME" VARCHAR2(128 CHAR),
"PF_OWNER" VARCHAR2(128 CHAR),
"PACKAGE" VARCHAR2(128 CHAR),
"FUNCTION" VARCHAR2(128 CHAR),
"SEL" VARCHAR2(3 CHAR),
"INS" VARCHAR2(3 CHAR),
"UPD" VARCHAR2(3 CHAR),
"DEL" VARCHAR2(3 CHAR),
"IDX" VARCHAR2(3 CHAR),
"CHK_OPTION" VARCHAR2(3 CHAR),
"ENABLE" VARCHAR2(3 CHAR),
"STATIC_POLICY" VARCHAR2(3 CHAR),
"POLICY_TYPE" VARCHAR2(24 CHAR),
"LONG_PREDICATE" VARCHAR2(3 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_ROLE_PRIVS"
(
"GRANTEE" VARCHAR2(128 CHAR),
"GRANTED_ROLE" VARCHAR2(128 CHAR),
"ADMIN_OPTION" VARCHAR2(3 CHAR),
"DELEGATE_OPTION" VARCHAR2(3 CHAR),
"DEFAULT_ROLE" VARCHAR2(3 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_JAVA_POLICY"
(
"KIND" VARCHAR2(8 CHAR),
"GRANTEE" VARCHAR2(128 CHAR),
"TYPE_SCHEMA" VARCHAR2(128 CHAR),
"TYPE_NAME" VARCHAR2(4000 CHAR),
"NAME" VARCHAR2(4000 CHAR),
"ACTION" VARCHAR2(4000 CHAR),
"ENABLED" VARCHAR2(8 CHAR),
"SEQ" NUMBER,
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_SCHEDULER_JOBS"
(
"OWNER" VARCHAR2(128 CHAR),
"JOB_NAME" VARCHAR2(128 CHAR),
"JOB_SUBNAME" VARCHAR2(128 CHAR),
"JOB_STYLE" VARCHAR2(17 CHAR),
"JOB_CREATOR" VARCHAR2(128 CHAR),
"CLIENT_ID" VARCHAR2(65 CHAR),
"GLOBAL_UID" VARCHAR2(33 CHAR),
"PROGRAM_OWNER" VARCHAR2(4000 CHAR),
"PROGRAM_NAME" VARCHAR2(4000 CHAR),
"JOB_TYPE" VARCHAR2(16 CHAR),
"JOB_ACTION" VARCHAR2(4000 CHAR),
"NUMBER_OF_ARGUMENTS" NUMBER,
"SCHEDULE_OWNER" VARCHAR2(4000 CHAR),
"SCHEDULE_NAME" VARCHAR2(4000 CHAR),
"SCHEDULE_TYPE" VARCHAR2(12 CHAR),
"START_DATE" TIMESTAMP (6) WITH TIME ZONE,
"REPEAT_INTERVAL" VARCHAR2(4000 CHAR),
"EVENT_QUEUE_OWNER" VARCHAR2(128 CHAR),
"EVENT_QUEUE_NAME" VARCHAR2(128 CHAR),
"EVENT_QUEUE_AGENT" VARCHAR2(523 CHAR),
"EVENT_CONDITION" VARCHAR2(4000 CHAR),
"EVENT_RULE" VARCHAR2(261 CHAR),
"FILE_WATCHER_OWNER" VARCHAR2(261 CHAR),
"FILE_WATCHER_NAME" VARCHAR2(261 CHAR),
"END_DATE" TIMESTAMP (6) WITH TIME ZONE,
"JOB_CLASS" VARCHAR2(128 CHAR),
"ENABLED" VARCHAR2(5 CHAR),
"AUTO_DROP" VARCHAR2(5 CHAR),
"RESTART_ON_RECOVERY" VARCHAR2(5 CHAR),
"RESTART_ON_FAILURE" VARCHAR2(5 CHAR),
"STATE" VARCHAR2(15 CHAR),
"JOB_PRIORITY" NUMBER,
"RUN_COUNT" NUMBER,
"UPTIME_RUN_COUNT" NUMBER,
"MAX_RUNS" NUMBER,
"FAILURE_COUNT" NUMBER,
"UPTIME_FAILURE_COUNT" NUMBER,
"MAX_FAILURES" NUMBER,
"RETRY_COUNT" NUMBER,
"LAST_START_DATE" TIMESTAMP (6) WITH TIME ZONE,
"LAST_RUN_DURATION" INTERVAL DAY (9) TO SECOND (6),
"NEXT_RUN_DATE" TIMESTAMP (6) WITH TIME ZONE,
"SCHEDULE_LIMIT" INTERVAL DAY (3) TO SECOND (0),
"MAX_RUN_DURATION" INTERVAL DAY (3) TO SECOND (0),
"LOGGING_LEVEL" VARCHAR2(11 CHAR),
"STORE_OUTPUT" VARCHAR2(5 CHAR),
"STOP_ON_WINDOW_CLOSE" VARCHAR2(5 CHAR),
"INSTANCE_STICKINESS" VARCHAR2(5 CHAR),
"RAISE_EVENTS" VARCHAR2(4000 CHAR),
"SYSTEM" VARCHAR2(5 CHAR),
"JOB_WEIGHT" NUMBER,
"NLS_ENV" VARCHAR2(4000 CHAR),
"SOURCE" VARCHAR2(128 CHAR),
"NUMBER_OF_DESTINATIONS" NUMBER,
"DESTINATION_OWNER" VARCHAR2(261 CHAR),
"DESTINATION" VARCHAR2(261 CHAR),
"CREDENTIAL_OWNER" VARCHAR2(128 CHAR),
"CREDENTIAL_NAME" VARCHAR2(128 CHAR),
"INSTANCE_ID" NUMBER,
"DEFERRED_DROP" VARCHAR2(5 CHAR),
"ALLOW_RUNS_IN_RESTRICTED_MODE" VARCHAR2(5 CHAR),
"COMMENTS" VARCHAR2(4000 CHAR),
"FLAGS" NUMBER,
"RESTARTABLE" VARCHAR2(5 CHAR),
"HAS_CONSTRAINTS" VARCHAR2(5 CHAR),
"CONNECT_CREDENTIAL_OWNER" VARCHAR2(128 CHAR),
"CONNECT_CREDENTIAL_NAME" VARCHAR2(128 CHAR),
"FAIL_ON_SCRIPT_ERROR" VARCHAR2(5 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_AUDIT_POLICIES"
(
"OBJECT_SCHEMA" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"POLICY_OWNER" VARCHAR2(128 CHAR),
"POLICY_NAME" VARCHAR2(128 CHAR),
"POLICY_TEXT" VARCHAR2(4000 CHAR),
"POLICY_COLUMN" VARCHAR2(128 CHAR),
"PF_SCHEMA" VARCHAR2(128 CHAR),
"PF_PACKAGE" VARCHAR2(128 CHAR),
"PF_FUNCTION" VARCHAR2(128 CHAR),
"ENABLED" VARCHAR2(3 CHAR),
"SEL" VARCHAR2(3 CHAR),
"INS" VARCHAR2(3 CHAR),
"UPD" VARCHAR2(3 CHAR),
"DEL" VARCHAR2(3 CHAR),
"AUDIT_TRAIL" VARCHAR2(12 CHAR),
"POLICY_COLUMN_OPTIONS" VARCHAR2(11 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_SYS_PRIVS"
(
"GRANTEE" VARCHAR2(128 CHAR),
"PRIVILEGE" VARCHAR2(40 CHAR),
"ADMIN_OPTION" VARCHAR2(3 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_SYNONYMS"
(
"OWNER" VARCHAR2(128 CHAR),
"SYNONYM_NAME" VARCHAR2(128 CHAR),
"TABLE_OWNER" VARCHAR2(128 CHAR),
"TABLE_NAME" VARCHAR2(128 CHAR),
"DB_LINK" VARCHAR2(128 CHAR),
"ORIGIN_CON_ID" NUMBER,
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_HASH"
(
"OWNER" VARCHAR2(128 CHAR),
"NAME" VARCHAR2(128 CHAR),
"TYPE" VARCHAR2(12 CHAR),
"ORIGIN_CON_ID" NUMBER,
"CON_ID" NUMBER,
"MD5_ENC" RAW(16) NOT NULL,
"SHA1_ENC" RAW(20) NOT NULL,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL,
"CODE" CLOB NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_REGISTRY_SQLPATCH"
(
"INSTALL_ID" NUMBER,
"PATCH_ID" NUMBER,
"PATCH_UID" NUMBER,
"PATCH_TYPE" VARCHAR2(10 CHAR),
"ACTION" VARCHAR2(15 CHAR),
"STATUS" VARCHAR2(25 CHAR),
"ACTION_TIME" TIMESTAMP (6),
"DESCRIPTION" VARCHAR2(100 CHAR),
"LOGFILE" VARCHAR2(500 CHAR),
"RU_LOGFILE" VARCHAR2(500 CHAR),
"FLAGS" VARCHAR2(10 CHAR),
"PATCH_DESCRIPTOR" "SYS"."XMLTYPE" ,
"PATCH_DIRECTORY" BLOB,
"SOURCE_VERSION" VARCHAR2(15 CHAR),
"SOURCE_BUILD_DESCRIPTION" VARCHAR2(80 CHAR),
"SOURCE_BUILD_TIMESTAMP" TIMESTAMP (6),
"TARGET_VERSION" VARCHAR2(15 CHAR),
"TARGET_BUILD_DESCRIPTION" VARCHAR2(80 CHAR),
"TARGET_BUILD_TIMESTAMP" TIMESTAMP (6),
"VERSION" VARCHAR2(20 CHAR),
"BUNDLE_SERIES" VARCHAR2(30 CHAR),
"BUNDLE_ID" NUMBER,
"BUNDLE_DATA" "SYS"."XMLTYPE" ,
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_REALM"
(
"NAME" VARCHAR2(128 CHAR),
"DESCRIPTION" VARCHAR2(1024 CHAR),
"AUDIT_OPTIONS" NUMBER,
"REALM_TYPE" VARCHAR2(9 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"ENABLED" VARCHAR2(1 CHAR),
"ID#" NUMBER,
"ORACLE_SUPPLIED" VARCHAR2(3 CHAR),
"PL_SQL_STACK" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_REALM_AUTH"
(
"REALM_NAME" VARCHAR2(128 CHAR),
"COMMON_REALM" VARCHAR2(3 CHAR),
"INHERITED_REALM" VARCHAR2(3 CHAR),
"GRANTEE" VARCHAR2(128 CHAR),
"AUTH_RULE_SET_NAME" VARCHAR2(128 CHAR),
"AUTH_OPTIONS" VARCHAR2(4000 CHAR),
"COMMON_AUTH" VARCHAR2(3 CHAR),
"INHERITED_AUTH" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_RULE"
(
"NAME" VARCHAR2(128 CHAR),
"RULE_EXPR" VARCHAR2(1024 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"ID#" NUMBER,
"ORACLE_SUPPLIED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_RULE_SET"
(
"RULE_SET_NAME" VARCHAR2(128 CHAR),
"DESCRIPTION" VARCHAR2(1024 CHAR),
"ENABLED" VARCHAR2(1 CHAR),
"EVAL_OPTIONS_MEANING" VARCHAR2(4000 CHAR),
"AUDIT_OPTIONS" NUMBER,
"FAIL_OPTIONS_MEANING" VARCHAR2(4000 CHAR),
"FAIL_MESSAGE" VARCHAR2(80 CHAR),
"FAIL_CODE" VARCHAR2(10 CHAR),
"HANDLER_OPTIONS" NUMBER,
"HANDLER" VARCHAR2(1024 CHAR),
"IS_STATIC" VARCHAR2(5 CHAR),
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"ID#" NUMBER,
"ORACLE_SUPPLIED" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_COMMAND_RULE"
(
"COMMAND" VARCHAR2(128 CHAR),
"CLAUSE_NAME" VARCHAR2(100 CHAR),
"PARAMETER_NAME" VARCHAR2(128 CHAR),
"EVENT_NAME" VARCHAR2(128 CHAR),
"COMPONENT_NAME" VARCHAR2(128 CHAR),
"ACTION_NAME" VARCHAR2(128 CHAR),
"RULE_SET_NAME" VARCHAR2(128 CHAR),
"OBJECT_OWNER" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"ENABLED" VARCHAR2(1 CHAR),
"PRIVILEGE_SCOPE" NUMBER,
"COMMON" VARCHAR2(3 CHAR),
"INHERITED" VARCHAR2(3 CHAR),
"ID#" NUMBER,
"ORACLE_SUPPLIED" VARCHAR2(3 CHAR),
"PL_SQL_STACK" VARCHAR2(3 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;

CREATE TABLE "T_DV_REALM_OBJECT"
(
"REALM_NAME" VARCHAR2(128 CHAR),
"COMMON_REALM" VARCHAR2(3 CHAR),
"INHERITED_REALM" VARCHAR2(3 CHAR),
"OWNER" VARCHAR2(128 CHAR),
"OBJECT_NAME" VARCHAR2(128 CHAR),
"OBJECT_TYPE" VARCHAR2(32 CHAR),
"CON_ID" NUMBER,
"SERIES" VARCHAR2(10 CHAR) NOT NULL,
"ORAVERSION" VARCHAR2(20 CHAR) NOT NULL,
"PSU" NUMBER NOT NULL
)
COMPRESS NOLOGGING;