WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_TXTCOLLECTION_LOAD PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE T_TXTCOLLECTION_LOAD
(
  FILE_NAME   VARCHAR2(50)  NOT NULL,
  PATH        VARCHAR2(500) NOT NULL,
  CONTENTS    CLOB NOT NULL,
  MD5_HASH    RAW(16)
)
COMPRESS NOLOGGING;