BEGIN EXECUTE IMMEDIATE 'alter table &&1. DROP COLUMN HASH_LINE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'alter table &&1. ADD (HASH_LINE_ID RAW(16))'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

UPDATE &&1. SET HASH_LINE_ID=NULL WHERE HASH_LINE_ID IS NOT NULL;

COMMIT;

UNDEF 1