WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_FILES_LOAD PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE T_FILES_LOAD
(
  FILE_NAME  VARCHAR2(50)  NOT NULL,
  HASH       RAW(32)       NOT NULL,
  PATH       VARCHAR2(500) NOT NULL,
  FILE_TYPE  VARCHAR2(1 CHAR) NOT NULL
)
COMPRESS NOLOGGING;